### ISSUE TITLE
Add Sensor Model Class

### ISSUE THREAD

**Issue by SillyInventor** [CSDTs/SGIS-backend#14]
We want to add data to the database for particular sensors. So one thing that needs to be done is add a sensor model. That should have:
Name (string)
Supplier (string)
Model (string)
Metric (string)
Accuracy (string)

**Comment by Timothyw0** [comment]
Is this just adding a sensor class with the attributes in model.py? Or is there something else to do? Like connecting it in other files

**Comment by SillyInventor** [comment]
To alter the database, just create the class in models, then make a migration, and migrate. Make sure the migration gets added.

However, it would also be a good idea to add a viewset (currently in views.py) so you can debug.

**Comment by Timothyw0** [comment]
Model added and migration was successful
